openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /login:
    $ref: paths/login.yml
  /password/change:
    $ref: paths/password_change.yml
  /password/reset/{token}:
    $ref: paths/password_reset.yml
  /account:
    $ref: paths/accounts.yml
  /security/login/register:
    $ref: paths/login_register.yml