<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.framework.security</groupId>
      <artifactId>login</artifactId>
      <version>1.0.0-SNAPSHOT</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.framework.security</groupId>
   <artifactId>login-usecase</artifactId>
   <packaging>jar</packaging>

   <name>Security login usecase</name>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <!-- ============================================== -->
      <!-- ================ FRAMEWORK =================== -->
      <!-- ============================================== -->
      <dependency>
         <!-- JWT Encoding -->
         <groupId>com.bernardomg.framework.jwt</groupId>
         <artifactId>jwt-encoding</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================= PROJECT ==================== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>domain</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>user</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>login-domain</artifactId>
      </dependency>
   </dependencies>

</project>
