<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.framework.security</groupId>
      <artifactId>security-starter</artifactId>
      <version>1.0.0-SNAPSHOT</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.framework.security</groupId>
   <artifactId>security-usecase</artifactId>
   <packaging>jar</packaging>

   <name>Security usecase</name>

   <!-- ********************************************** -->
   <!-- **************** PROPERTIES ****************** -->
   <!-- ********************************************** -->

   <properties>
      <!-- ============================================== -->
      <!-- =============== MANIFEST DATA ================ -->
      <!-- ============================================== -->
      <manifest.name>com/bernardomg/security/security/usecase</manifest.name>
   </properties>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <!-- ============================================== -->
      <!-- ================ FRAMEWORK =================== -->
      <!-- ============================================== -->
      <dependency>
         <!-- JWT Encoding -->
         <groupId>com.bernardomg.framework.jwt</groupId>
         <artifactId>jwt-encoding</artifactId>
      </dependency>
      <dependency>
         <!-- Validation -->
         <groupId>com.bernardomg.framework</groupId>
         <artifactId>validation</artifactId>
      </dependency>
      <dependency>
         <!-- Pagination -->
         <groupId>com.bernardomg.framework</groupId>
         <artifactId>pagination</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================= PROJECT ==================== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>security-model</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================== JAKARTA =================== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>jakarta.transaction</groupId>
         <artifactId>jakarta.transaction-api</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ============== APACHE COMMONS ================ -->
      <!-- ============================================== -->
      <dependency>
         <groupId>org.apache.commons</groupId>
         <artifactId>commons-lang3</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ======= TEST ENVIRONMENT DEPENDENCIES ======== -->
      <!-- ============================================== -->
      <dependency>
         <!-- AssertJ -->
         <groupId>org.assertj</groupId>
         <artifactId>assertj-core</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <!-- JUnit Jupiter Engine -->
         <groupId>org.junit.jupiter</groupId>
         <artifactId>junit-jupiter-engine</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <!-- Mockito -->
         <groupId>org.mockito</groupId>
         <artifactId>mockito-core</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <!-- Mockito -->
         <groupId>org.mockito</groupId>
         <artifactId>mockito-junit-jupiter</artifactId>
         <scope>test</scope>
      </dependency>
   </dependencies>

</project>
