<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.framework.security</groupId>
      <artifactId>security-starter</artifactId>
      <version>0.5.9</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.framework.spring</groupId>
   <artifactId>spring-ws-security-starter</artifactId>
   <packaging>jar</packaging>

   <name>Starter for Security in Spring Web Services</name>
   <description>Starter for Security in Spring Web Services.</description>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <!-- ============================================== -->
      <!-- ================= PROJECT ==================== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>security-usecase</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>security-adapter</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.framework.security.spring</groupId>
         <artifactId>spring-security</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- =============== SPRING BOOT ================== -->
      <!-- ============================================== -->
      <dependency>
         <!-- Spring Boot Autoconfigure -->
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-autoconfigure</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================== JAKARTA =================== -->
      <!-- ============================================== -->
      <dependency>
          <!-- Jakarta Servlet API -->
         <groupId>jakarta.servlet</groupId>
         <artifactId>jakarta.servlet-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <!-- ============================================== -->
      <!-- ======= TEST ENVIRONMENT DEPENDENCIES ======== -->
      <!-- ============================================== -->
      <dependency>
         <!-- JUnit Jupiter Engine -->
         <groupId>org.junit.jupiter</groupId>
         <artifactId>junit-jupiter-engine</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <!-- Architecture Tests -->
         <groupId>com.bernardomg.framework.testing</groupId>
         <artifactId>architecture-tests</artifactId>
      </dependency>
      <dependency>
         <!-- ArchUnit -->
         <groupId>com.tngtech.archunit</groupId>
         <artifactId>archunit-junit5</artifactId>
         <scope>test</scope>
      </dependency>
   </dependencies>

   <!-- ********************************************** -->
   <!-- ******************* BUILD ******************** -->
   <!-- ********************************************** -->

   <build>
      <defaultGoal>clean package</defaultGoal>
   </build>

</project>
