openapi: 3.0.3
info:
  title: Security API
  version: 1.0.0
  description: Security API.
servers:
  - url: https://localhost
    description: Local development
paths:
  /security/role:
    $ref: paths/roles.yml
  /security/role/{name}:
    $ref: paths/roles_by_id.yml