openapi: 3.0.3
info:
  title: Security API
  version: 1.0.0
  description: Security API.
servers:
  - url: https://localhost
    description: Local development
paths:
  /security/permission:
    $ref: paths/permissions.yml