<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.framework.security</groupId>
      <artifactId>security-starter</artifactId>
      <version>0.5.5</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.framework.security</groupId>
   <artifactId>security-jpa-model</artifactId>
   <packaging>jar</packaging>

   <name>Security JPA model</name>

   <!-- ********************************************** -->
   <!-- **************** PROPERTIES ****************** -->
   <!-- ********************************************** -->

   <properties>
      <!-- ============================================== -->
      <!-- =============== MANIFEST DATA ================ -->
      <!-- ============================================== -->
      <manifest.name>com/bernardomg/security/security/jpa/model</manifest.name>
   </properties>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <!-- ============================================== -->
      <!-- ================= PROJECT ==================== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>security-model</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ============== JPA DEPENDENCIES ============== -->
      <!-- ============================================== -->
      <dependency>
         <!-- JPA API -->
         <groupId>jakarta.persistence</groupId>
         <artifactId>jakarta.persistence-api</artifactId>
      </dependency>
   </dependencies>

</project>
